### ISSUE TITLE
Warning Messages during run

### ISSUE THREAD

**Issue by pakiessling** [livnatje/DIALOGUE#26]
Hi Livnat,

thank you for the tool. During the run I receive warning messages such as hundreds of lines of:

`boundary (singular) fit: see help('isSingular')`

and at the end:
```
NULL
NULL
NULL
Warning message:
In cor.test.default(v1[, i], x, method = method, use = use, alternative = alternative) :
  Cannot compute exact p-value with ties
```

Does that just mean that lme4 is struggling to find something or is there something wrong with my installation or input?
Thank you for your help

**Comment by livnatje** [comment]
Hi @pakiessling,

How many samples/cells do you have as input here?

The singular error is from the HLM step (lmer), and is probably because the model is too complex (i.e., overfitting) to a dataset that is too small. You can see more information about singularity here https://rdrr.io/cran/lme4/man/isSingular.html

As for the warning message, this is due to ties in the Spearman correlation test.

Thanks

**Comment by livnatje** [comment]
Hi @pakiessling , I'm closing this issue for now, but let me know if you have any additional questions. Thanks
