### ISSUE TITLE
scRNA data cell number limit

### ISSUE THREAD

**Issue by zhangqi234** [livnatje/DIALOGUE#30]
Hello,
First of all, thanks for the great tool and thank you for your research! I’d like to know whether this tool has a limit on the number of single cells data. Thank you very much！

**Comment by tomgome** [comment]
hi,
same question and a follow-up question:
what about scRNA-seq datasets with (sometimes highly) imbalanced cell types? how do you expect it to affect the output?

(sorry if I'm hijacking the thread)

**Comment by livnatje** [comment]
Thank you @zhangqi234. Can you explain what you mean by "number of single cells data"? Do you mean combining different datasets (e.g., from different studies) to perform meta-analyses? That is possible, as long as you are (1) providing the input after batch correction, and/or (2) add a covariate in the second step to account for the dataset as a potential confounder.

@tomgome, I don't expect this will have a major effect as DIALOGUE is requiring that all pairwise analyses of cell types will support the MCP. This may impact the ability to identify MCPs across many different cell types because the less frequent cell types will decrease the statistical power of the models.
