### ISSUE TITLE
Impossible to reproduce the code

### ISSUE THREAD

**Issue by elissonlopes** [livnatje/DIALOGUE#31]
Please upload this package ASAP. 
Many functions without any explanation how to use or set parameters. I never saw a package with so little documentation.  
Even running examples I got error messages. 
The nature paper is beautiful but the package needs to be update or is impossible to reproduce the results you presented.

**Comment by livnatje** [comment]
Are you experiencing any specific problem? 

Have you seen the tutorial? https://github.com/livnatje/DIALOGUE/wiki/Tutorial
And the toy example? https://github.com/livnatje/DIALOGUE/wiki/Example

The documentation of the package is also provided in the R embedded "help" feature, which you can access by using "?" followed by the function name

**Comment by elissonlopes** [comment]
Yes. Since the first function I got error. I solved it adding a missing "NK" to generate the r2. It took me a time to do it, because of this lack of descriptions.

Its a potential package and great ideia.
  
But more than 2k lines of R code without explanation about parameters (input and output), how to adapt the run to different types of data etc. 

I would like to recommend you to add more info, please. It would help a lot for anyone how wants at least reproduce what you presented in the paper.

**Comment by elissonlopes** [comment]
Test using DIALOGUE_SeuratExample with pbmc data

**Comment by livnatje** [comment]
@elissonlopes, the Seurat wrapper is not an integral part of DIALOGUE. We added this as a curtesy to address GitHub requests and make it easier for users.

You may have had issues with the example because the toy data is fairly small and there was another criteria recently added to ensure sufficient statistical power. This issue was now resolved, and you can see the documentation here 
https://github.com/livnatje/DIALOGUE/wiki/Toy-example:-Running-DIALOGUE-with-Seurat-object

Note that other than the documentation in GitHub you can also look at the R documentation directly

```
> ?DIALOGUE.run
> ?make.cell.type
> ?DIALOGUE.plot
> ?DIALOGUE_make.cell.type.seurat
```
As explained in detail in the `?DIALOGUE.run` documentation, you essentially need to provide the gene expression per cell type and number of MCPs. It's fairly plug and play with a lot happening backend in a data driven manner (hence the many lines of code).
