### ISSUE TITLE
How to validate the MCPs expression

### ISSUE THREAD

**Issue by Xxhongs** [livnatje/DIALOGUE#32]
Hi @livnatje, DIALOGUE provides the MCPs expression by the DLG.find.scoring function, so if i get some MCPs in scRNA data and want to calculate the overall expression of MCPs in another dataset(e.g. bulk RNA data). What is the process? Perhaps filtering MCPs genes and obtaining a zscores matrix?

Could you briefly introduce the program.

Thanks.

**Comment by Xxhongs** [comment]
I found the description and code for the bulk data in the previous CELL article, which helped me a lot.

**Comment by livnatje** [comment]
Great! Thanks for the update!

**Comment by andrewjkwok** [comment]
Hi @Xxhongs - just wondering whether you had any success using DIALOGUE for bulk RNA-seq in the end, and what the previous cell article was that you were referring to for the description and code? 

@livnatje - did you have any recommendations for whether DIALOGUE could be run for bulk RNA-seq +/- what kind of modifications might be appropriate?

Many thanks in advance.

**Comment by livnatje** [comment]
Hi @andrewjkwok, bulk RNA-seq could work if cell types are sequences separately (each in bulk) from large enough number of samples (at least 15-20).

Alternatively, if you have a reliable way to deconvolve the bulk RNA of a single sample to the respective cell type specific profiles first. The confidence in the results in that case will also depend on the deconvolution accuracy.

Hope this helps

**Comment by QiangShiPKU** [comment]
@livnatje @Xxhongs Thank you both for your valuable input. However, I still have a question regarding the calculation of MCP overall expression (OE) in bulk RNA-seq data, similar to Fig4f and Fig5e in your paper. An MCP consists of multiple gene sets categorized by cell types and direction (up- or down-regulation), such as A_up, A_down, B_up, and B_down. Therefore, in order to obtain OE, should I aggregate all gene sets across different cell types, or should I separately aggregate the up- and down-regulated gene sets?
